export interface AndroidInstalledApp {
  id: string;
  name: string;
  packageName: string;
  category: "Social" | "UPI & Pay" | "Media" | "Shopping & Food" | "Travel" | "Google & System";
  gradient: string;
  badgeText: string;
  nativeScheme?: string;
  webUrl: string;
  searchUrlTemplate?: string;
  internalAction?: string;
  permissionsGranted: string[];
}

export const ALL_ANDROID_APPS: AndroidInstalledApp[] = [
  // --- SOCIAL & MESSAGING ---
  {
    id: "whatsapp",
    name: "WhatsApp",
    packageName: "com.whatsapp",
    category: "Social",
    gradient: "from-emerald-500 to-green-600",
    badgeText: "WA",
    nativeScheme: "whatsapp://send",
    webUrl: "https://web.whatsapp.com",
    permissionsGranted: ["Contacts", "Microphone", "Camera", "Notifications"],
  },
  {
    id: "instagram",
    name: "Instagram",
    packageName: "com.instagram.android",
    category: "Social",
    gradient: "from-pink-500 via-rose-500 to-amber-500",
    badgeText: "IG",
    nativeScheme: "instagram://app",
    webUrl: "https://www.instagram.com",
    permissionsGranted: ["Camera", "Microphone", "Storage"],
  },
  {
    id: "facebook",
    name: "Facebook",
    packageName: "com.facebook.katana",
    category: "Social",
    gradient: "from-blue-600 to-blue-700",
    badgeText: "FB",
    nativeScheme: "fb://root",
    webUrl: "https://www.facebook.com",
    permissionsGranted: ["Location", "Camera", "Notifications"],
  },
  {
    id: "telegram",
    name: "Telegram",
    packageName: "org.telegram.messenger",
    category: "Social",
    gradient: "from-sky-400 to-blue-600",
    badgeText: "TG",
    nativeScheme: "tg://resolve",
    webUrl: "https://web.telegram.org",
    permissionsGranted: ["Contacts", "Storage", "Microphone"],
  },
  {
    id: "snapchat",
    name: "Snapchat",
    packageName: "com.snapchat.android",
    category: "Social",
    gradient: "from-yellow-400 to-amber-500",
    badgeText: "SC",
    nativeScheme: "snapchat://",
    webUrl: "https://web.snapchat.com",
    permissionsGranted: ["Camera", "Location", "Microphone"],
  },
  {
    id: "twitter",
    name: "X (Twitter)",
    packageName: "com.twitter.android",
    category: "Social",
    gradient: "from-neutral-700 to-neutral-950",
    badgeText: "X",
    nativeScheme: "twitter://timeline",
    webUrl: "https://x.com",
    searchUrlTemplate: "https://x.com/search?q={query}",
    permissionsGranted: ["Notifications", "Media"],
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    packageName: "com.linkedin.android",
    category: "Social",
    gradient: "from-blue-700 to-sky-600",
    badgeText: "IN",
    webUrl: "https://www.linkedin.com",
    permissionsGranted: ["Contacts", "Notifications"],
  },
  {
    id: "truecaller",
    name: "Truecaller",
    packageName: "com.truecaller",
    category: "Social",
    gradient: "from-blue-500 to-indigo-600",
    badgeText: "TC",
    webUrl: "https://www.truecaller.com",
    permissionsGranted: ["Call Logs", "Phone", "Contacts"],
  },
  {
    id: "threads",
    name: "Threads",
    packageName: "com.instagram.barcelona",
    category: "Social",
    gradient: "from-slate-800 to-black",
    badgeText: "@",
    webUrl: "https://www.threads.net",
    permissionsGranted: ["Camera", "Notifications"],
  },
  {
    id: "discord",
    name: "Discord",
    packageName: "com.discord",
    category: "Social",
    gradient: "from-indigo-500 to-purple-600",
    badgeText: "DC",
    webUrl: "https://discord.com/app",
    permissionsGranted: ["Microphone", "Notifications"],
  },

  // --- UPI, PAYMENTS & BANKING ---
  {
    id: "gpay",
    name: "Google Pay (GPay)",
    packageName: "com.google.android.apps.nbu.paisa.user",
    category: "UPI & Pay",
    gradient: "from-blue-600 via-indigo-500 to-emerald-500",
    badgeText: "GPay",
    nativeScheme: "tez://upi/",
    webUrl: "https://pay.google.com",
    permissionsGranted: ["Camera (QR)", "Location", "SMS", "Phone"],
  },
  {
    id: "phonepe",
    name: "PhonePe",
    packageName: "com.phonepe.app",
    category: "UPI & Pay",
    gradient: "from-purple-600 to-indigo-700",
    badgeText: "Pe",
    nativeScheme: "phonepe://",
    webUrl: "https://www.phonepe.com",
    permissionsGranted: ["Camera (QR)", "Location", "SMS", "Contacts"],
  },
  {
    id: "paytm",
    name: "Paytm",
    packageName: "net.one97.paytm",
    category: "UPI & Pay",
    gradient: "from-sky-500 to-blue-700",
    badgeText: "Paytm",
    nativeScheme: "paytmmp://",
    webUrl: "https://paytm.com",
    permissionsGranted: ["Camera (QR)", "Contacts", "SMS"],
  },
  {
    id: "bhim",
    name: "BHIM UPI",
    packageName: "in.org.npci.upiapp",
    category: "UPI & Pay",
    gradient: "from-orange-500 to-emerald-600",
    badgeText: "UPI",
    nativeScheme: "upi://pay",
    webUrl: "https://www.bhimupi.org.in",
    permissionsGranted: ["SMS", "Phone", "Camera"],
  },
  {
    id: "cred",
    name: "CRED",
    packageName: "com.dreamplug.androidapp",
    category: "UPI & Pay",
    gradient: "from-zinc-800 to-neutral-950",
    badgeText: "CRED",
    webUrl: "https://cred.club",
    permissionsGranted: ["SMS", "Camera", "Notifications"],
  },

  // --- ENTERTAINMENT & MEDIA ---
  {
    id: "youtube",
    name: "YouTube",
    packageName: "com.google.android.youtube",
    category: "Media",
    gradient: "from-red-600 to-rose-600",
    badgeText: "YT",
    nativeScheme: "vnd.youtube://",
    webUrl: "https://www.youtube.com",
    searchUrlTemplate: "https://www.youtube.com/results?search_query={query}",
    permissionsGranted: ["Microphone", "Notifications", "Background Audio"],
  },
  {
    id: "ytmusic",
    name: "YouTube Music",
    packageName: "com.google.android.apps.youtube.music",
    category: "Media",
    gradient: "from-rose-600 to-red-800",
    badgeText: "YTM",
    webUrl: "https://music.youtube.com",
    searchUrlTemplate: "https://music.youtube.com/search?q={query}",
    permissionsGranted: ["Background Audio", "Storage"],
  },
  {
    id: "spotify",
    name: "Spotify",
    packageName: "com.spotify.music",
    category: "Media",
    gradient: "from-green-500 to-emerald-700",
    badgeText: "SP",
    nativeScheme: "spotify://",
    webUrl: "https://open.spotify.com",
    searchUrlTemplate: "https://open.spotify.com/search/{query}",
    permissionsGranted: ["Background Audio", "Bluetooth", "Notifications"],
  },
  {
    id: "jiocinema",
    name: "JioCinema",
    packageName: "com.jio.media.ondemand",
    category: "Media",
    gradient: "from-pink-600 to-purple-700",
    badgeText: "Jio",
    webUrl: "https://www.jiocinema.com",
    permissionsGranted: ["Media", "Network"],
  },
  {
    id: "hotstar",
    name: "Disney+ Hotstar",
    packageName: "in.startv.hotstar",
    category: "Media",
    gradient: "from-blue-800 to-indigo-950",
    badgeText: "D+",
    webUrl: "https://www.hotstar.com",
    permissionsGranted: ["Storage", "Notifications"],
  },
  {
    id: "netflix",
    name: "Netflix",
    packageName: "com.netflix.mediaclient",
    category: "Media",
    gradient: "from-red-700 to-black",
    badgeText: "N",
    webUrl: "https://www.netflix.com",
    permissionsGranted: ["Storage", "Downloads"],
  },
  {
    id: "primevideo",
    name: "Prime Video",
    packageName: "com.amazon.avod.thirdpartyclient",
    category: "Media",
    gradient: "from-sky-500 to-blue-800",
    badgeText: "PV",
    webUrl: "https://www.primevideo.com",
    permissionsGranted: ["Storage", "Notifications"],
  },
  {
    id: "jiosaavn",
    name: "JioSaavn",
    packageName: "com.jio.media.jiobeats",
    category: "Media",
    gradient: "from-teal-400 to-emerald-600",
    badgeText: "JS",
    webUrl: "https://www.jiosaavn.com",
    permissionsGranted: ["Background Audio"],
  },

  // --- SHOPPING & FOOD DELIVERY ---
  {
    id: "amazon",
    name: "Amazon India",
    packageName: "in.amazon.mShop.android.shopping",
    category: "Shopping & Food",
    gradient: "from-amber-500 to-orange-600",
    badgeText: "AMZ",
    webUrl: "https://www.amazon.in",
    searchUrlTemplate: "https://www.amazon.in/s?k={query}",
    permissionsGranted: ["Location", "Camera", "Microphone"],
  },
  {
    id: "flipkart",
    name: "Flipkart",
    packageName: "com.flipkart.android",
    category: "Shopping & Food",
    gradient: "from-blue-600 to-yellow-500",
    badgeText: "FK",
    webUrl: "https://www.flipkart.com",
    searchUrlTemplate: "https://www.flipkart.com/search?q={query}",
    permissionsGranted: ["Location", "Notifications"],
  },
  {
    id: "zomato",
    name: "Zomato",
    packageName: "com.application.zomato",
    category: "Shopping & Food",
    gradient: "from-rose-600 to-red-700",
    badgeText: "ZOM",
    webUrl: "https://www.zomato.com",
    permissionsGranted: ["Precise Location", "Notifications"],
  },
  {
    id: "swiggy",
    name: "Swiggy",
    packageName: "in.swiggy.android",
    category: "Shopping & Food",
    gradient: "from-orange-500 to-amber-600",
    badgeText: "SWG",
    webUrl: "https://www.swiggy.com",
    permissionsGranted: ["Precise Location", "Phone"],
  },
  {
    id: "blinkit",
    name: "Blinkit",
    packageName: "com.grofers.customerapp",
    category: "Shopping & Food",
    gradient: "from-yellow-400 to-green-600",
    badgeText: "BLK",
    webUrl: "https://blinkit.com",
    permissionsGranted: ["Precise Location"],
  },
  {
    id: "zepto",
    name: "Zepto",
    packageName: "com.zeptoconsumerapp",
    category: "Shopping & Food",
    gradient: "from-purple-600 to-pink-600",
    badgeText: "ZEP",
    webUrl: "https://www.zeptonow.com",
    permissionsGranted: ["Precise Location"],
  },
  {
    id: "myntra",
    name: "Myntra",
    packageName: "com.myntra.android",
    category: "Shopping & Food",
    gradient: "from-pink-500 to-orange-500",
    badgeText: "MYN",
    webUrl: "https://www.myntra.com",
    permissionsGranted: ["Camera", "Notifications"],
  },
  {
    id: "meesho",
    name: "Meesho",
    packageName: "com.meesho.supply",
    category: "Shopping & Food",
    gradient: "from-fuchsia-600 to-pink-600",
    badgeText: "MSH",
    webUrl: "https://www.meesho.com",
    permissionsGranted: ["Storage", "Notifications"],
  },

  // --- TRAVEL & MAPS ---
  {
    id: "maps",
    name: "Google Maps",
    packageName: "com.google.android.apps.maps",
    category: "Travel",
    gradient: "from-emerald-500 via-teal-500 to-blue-600",
    badgeText: "MAP",
    nativeScheme: "geo:0,0?q=",
    webUrl: "https://maps.google.com",
    searchUrlTemplate: "https://www.google.com/maps/search/?api=1&query={query}",
    permissionsGranted: ["Background Location", "Compass", "GPS"],
  },
  {
    id: "uber",
    name: "Uber",
    packageName: "com.ubercab",
    category: "Travel",
    gradient: "from-zinc-800 to-black",
    badgeText: "UBR",
    webUrl: "https://m.uber.com",
    permissionsGranted: ["Background Location", "Phone"],
  },
  {
    id: "ola",
    name: "Ola Cabs",
    packageName: "com.olacabs.customer",
    category: "Travel",
    gradient: "from-lime-500 to-emerald-700",
    badgeText: "OLA",
    webUrl: "https://book.olacabs.com",
    permissionsGranted: ["Background Location", "Phone"],
  },
  {
    id: "rapido",
    name: "Rapido Bike-Taxi",
    packageName: "com.rapido.passenger",
    category: "Travel",
    gradient: "from-yellow-400 to-amber-600",
    badgeText: "RPD",
    webUrl: "https://www.rapido.bike",
    permissionsGranted: ["Location", "Phone"],
  },
  {
    id: "irctc",
    name: "IRCTC Rail Connect",
    packageName: "cris.org.in.prs.ima",
    category: "Travel",
    gradient: "from-blue-700 to-indigo-900",
    badgeText: "RAIL",
    webUrl: "https://www.irctc.co.in",
    permissionsGranted: ["Storage", "Notifications"],
  },
  {
    id: "makemytrip",
    name: "MakeMyTrip",
    packageName: "com.makemytrip",
    category: "Travel",
    gradient: "from-red-600 to-blue-700",
    badgeText: "MMT",
    webUrl: "https://www.makemytrip.com",
    permissionsGranted: ["Location", "SMS"],
  },

  // --- GOOGLE & SYSTEM TOOLS ---
  {
    id: "camera",
    name: "4K Camera",
    packageName: "com.android.camera2",
    category: "Google & System",
    gradient: "from-purple-600 to-indigo-600",
    badgeText: "CAM",
    webUrl: "#camera",
    internalAction: "camera",
    permissionsGranted: ["Camera", "Microphone", "Storage"],
  },
  {
    id: "phone",
    name: "Phone Dialer",
    packageName: "com.google.android.dialer",
    category: "Google & System",
    gradient: "from-green-500 to-emerald-600",
    badgeText: "CALL",
    webUrl: "#dialer",
    internalAction: "dialer",
    permissionsGranted: ["Phone", "Call Logs", "Contacts"],
  },
  {
    id: "contacts",
    name: "Contacts",
    packageName: "com.google.android.contacts",
    category: "Google & System",
    gradient: "from-cyan-500 to-blue-600",
    badgeText: "PPL",
    webUrl: "#contacts",
    internalAction: "contacts",
    permissionsGranted: ["Contacts", "Phone"],
  },
  {
    id: "clock",
    name: "Clock & Alarms",
    packageName: "com.google.android.deskclock",
    category: "Google & System",
    gradient: "from-amber-500 to-orange-600",
    badgeText: "ALM",
    webUrl: "#clock",
    internalAction: "clock",
    permissionsGranted: ["Exact Alarms", "Background Wake"],
  },
  {
    id: "settings",
    name: "Android Settings",
    packageName: "com.android.settings",
    category: "Google & System",
    gradient: "from-slate-600 to-slate-800",
    badgeText: "OS",
    webUrl: "#settings",
    internalAction: "settings",
    permissionsGranted: ["System Admin", "Hardware Modify"],
  },
  {
    id: "chrome",
    name: "Google Chrome",
    packageName: "com.android.chrome",
    category: "Google & System",
    gradient: "from-blue-500 via-amber-500 to-red-500",
    badgeText: "WEB",
    webUrl: "https://www.google.com",
    searchUrlTemplate: "https://www.google.com/search?q={query}",
    permissionsGranted: ["Internet", "Camera", "Location"],
  },
  {
    id: "gmail",
    name: "Gmail",
    packageName: "com.google.android.gm",
    category: "Google & System",
    gradient: "from-red-500 to-rose-700",
    badgeText: "MAIL",
    webUrl: "https://mail.google.com",
    permissionsGranted: ["Contacts", "Storage", "Notifications"],
  },
  {
    id: "playstore",
    name: "Google Play Store",
    packageName: "com.android.vending",
    category: "Google & System",
    gradient: "from-teal-400 via-blue-500 to-rose-500",
    badgeText: "PLAY",
    webUrl: "https://play.google.com/store/apps",
    searchUrlTemplate: "https://play.google.com/store/search?q={query}&c=apps",
    permissionsGranted: ["Install Packages", "Auto-Update"],
  },
  {
    id: "photos",
    name: "Google Photos",
    packageName: "com.google.android.apps.photos",
    category: "Google & System",
    gradient: "from-amber-500 via-pink-500 to-blue-500",
    badgeText: "IMG",
    webUrl: "https://photos.google.com",
    permissionsGranted: ["Media Library", "Cloud Backup"],
  },
  {
    id: "drive",
    name: "Google Drive",
    packageName: "com.google.android.apps.docs",
    category: "Google & System",
    gradient: "from-emerald-500 via-amber-500 to-blue-600",
    badgeText: "DRV",
    webUrl: "https://drive.google.com",
    permissionsGranted: ["Files & Storage"],
  },
  {
    id: "calendar",
    name: "Google Calendar",
    packageName: "com.google.android.calendar",
    category: "Google & System",
    gradient: "from-blue-500 to-indigo-600",
    badgeText: "CAL",
    webUrl: "https://calendar.google.com",
    permissionsGranted: ["Calendar Events", "Reminders"],
  },
  {
    id: "translate",
    name: "Google Translate",
    packageName: "com.google.android.apps.translate",
    category: "Google & System",
    gradient: "from-sky-500 to-blue-700",
    badgeText: "A/अ",
    webUrl: "https://translate.google.com",
    permissionsGranted: ["Microphone", "Camera"],
  },
  {
    id: "files",
    name: "Files by Google",
    packageName: "com.google.android.apps.nbu.files",
    category: "Google & System",
    gradient: "from-cyan-500 to-blue-600",
    badgeText: "FILE",
    webUrl: "#files",
    internalAction: "files",
    permissionsGranted: ["All Files Access (MANAGE_EXTERNAL_STORAGE)"],
  },
];

export function findAndroidAppByName(query: string): AndroidInstalledApp | undefined {
  const q = query.toLowerCase().trim();
  return ALL_ANDROID_APPS.find(
    (app) =>
      app.id.toLowerCase() === q ||
      app.name.toLowerCase() === q ||
      app.name.toLowerCase().includes(q) ||
      q.includes(app.id.toLowerCase()) ||
      app.packageName.toLowerCase().includes(q)
  );
}

export function resolveAppLaunchUrl(app: AndroidInstalledApp, searchQuery?: string): string {
  if (searchQuery && app.searchUrlTemplate) {
    return app.searchUrlTemplate.replace("{query}", encodeURIComponent(searchQuery));
  }
  return app.webUrl;
}
